### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by santosh653**
This PR is for PowerPC CPU support on Travis.

### CODE REVIEW

**Comment by MikeMcl** [comment]
Wouldn't that mean testing was only done on Power PC?

```
arch:
  - amd64
  - ppc64le
```

Perhaps `arm64` also, but is there any documentation confirming that Travis can run Node.js on these architectures without any further configuration?

**Comment by santosh653** [comment]
Adding power support ppc64le
This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing. For more info tag @gerrith3.

**Comment by gerrith3** [comment]
@MikeMcl we have added full support to production travis-ci.com for ppc64le backends.  We should have very close to full parity between ppc64le and amd64 images.  We do not support some older version of, say, python, but in general everything should be there.

**Comment by santosh653** [comment]
The build is successful on both arch: ppc64le & amd64, please refer to below link.
https://travis-ci.com/github/santosh653/bignumber.js

**Comment by MikeMcl** [comment]
Thank you.

**Pull request merged**
