### PR TITLE
fix: Sum of zero elements equals zero

### PR DESCRIPTION
**Pull request by artyomxyz**
I believe sum of zero elements equals zero. Current implementation produces NaN for this case.

### CODE REVIEW

**Comment by shuckster** [comment]
In plain JavaScript, how does the length of a set correlate with its type?

**Comment by MikeMcl** [comment]
Here, I don't think that convention would be useful.

If no set of elements is passed then there is no number of elements to count or sum, and so there is no number that can be returned.

Anyway, the current behaviour is consistent with other operations, e.g. `BigNumber(1).plus()`  // NaN`.

**Comment by MikeMcl** [comment]
I don't think that convention would be useful here. I think it is better to indicate a probable mistake with NaN.

The current behaviour is consistent with other operations, e.g. `BigNumber(1).plus() // NaN`.

**Comment by artyomxyz** [comment]
> I don't think that convention would be useful here. I think it is better to indicate a probable mistake with NaN.
> 
> 
> 
> The current behaviour is consistent with other operations, e.g. `BigNumber(1).plus() // NaN`.

Big difference here is that .plus expecting exactly one number, while sum expects set of numbers. And it is consistent with mathematical definition of sum

**Comment by MikeMcl** [comment]
> Big difference here is that .plus expects exactly one number, while sum expects set of numbers.

Sum expects one or more numbers. 

> Imagine we have a cart and products in it. 

Right, it's shopping, not formal mathematics.

How about:

```js
sum = BigNumber.sum(...cart.products.map(p => p.price));
if (sum.isNaN()) {
  if (cart.products.length === 0) handleEmptyCart(cart);
  else handleInvalidPrice(cart);
}
```
LGTM!

> For empty cart it's NaN. What kind of error we want to indicate here?

NaN is returned as a sentinel value which can be interpreted multifariously by code at a higher level of abstraction. 

> Still if we pass undefined as first argument we would receive NaN because it's an error.

Well, undefined is not a number, so that seems reasonable.

**Comment by MikeMcl** [comment]
> Big difference here is that .plus expects exactly one number, while sum expects set of numbers.

Here, sum expects one or more numbers. 

> Imagine we have a cart and products in it. 

Right, it's shopping, not formal mathematics.

> For empty cart it's NaN. What kind of error we want to indicate here?

That there is nothing to sum?

> Still if we pass undefined as first argument we would receive NaN because it's an error.

NaN is returned because undefined is not a number.

I agree that in some situations it would be useful for zero to be returned, but it would need to be applied consistently so:

```js
BigNumber();           // 0
BigNumber(1).plus();   // 1
BigNumber.sum();       // 0
// etc.
```

I will consider it further but I am not convinced atm.

**Pull request closed without merging**
