### PR TITLE
Bitwise methods

### PR DESCRIPTION
**Pull request by Vap0r1ze**
Hiya Mike, It's me from #106 I'm opening a fresh PR since I deleted my old fork. I _believe_ I addressed all of your concerns, but it's pretty late so I wouldn't be surprised if I missed something. Let me know what else there is to be done, or any issues you have with the PR in its current state.

### CODE REVIEW

**Comment by MikeMcl** [comment]
Hello again. 
I'll take a look at this properly this weekend.

**Comment by MikeMcl** [comment]
I quick first test of `bitShiftRight` seems to give the wrong answer:

```js
let n = new BigNumber(4);
n = n.bitShiftRight(1);
console.log(n.toString());    // '4'
console.log(4 >> 1);          // 2
```

**Comment by Vap0r1ze** [comment]
fixed that

**Comment by MikeMcl** [comment]
```js
console.log(BigNumber(9).and(57).toString());     // '2'
console.log(9 & 57);                              // 9
```

**Comment by MikeMcl** [comment]
```js
console.log(BigNumber(9).and(57).toString());     // 2
console.log(9 & 57);                              // 9

console.log(BigNumber(8).or(38).toString());      // 11
console.log(8 | 38);                              // 46

console.log(BigNumber(34).xor(89).toString());    // 61 
console.log(34 ^ 89);                             // 123

console.log(BigNumber(84).not().toString());      // NaN 
console.log(~84);                                 // -85
```

**Comment by Vap0r1ze** [comment]
oh i forgot tests, that would be important

**Comment by Vap0r1ze** [comment]
> Hello, can I help this feature?

Yea I think you'd just need to write tests dealing with all the methods dealing with special cases too for replicating the behaviour of `>>` and `<<`. Afterwards just bug fix from there.

**Comment by pwener** [comment]
Hi everyone, I submitted a PR at [Vap0r1ze:bitwise ](https://github.com/Vap0r1ze/bignumber.js/pull/1). I have a doubt, that you can answer too @MikeMcl , we can put all these test together at the same file?

**Comment by pwener** [comment]
@MikeMcl there is some issue here?

**Comment by MikeMcl** [comment]
Yes.

```js
BigInt(-3) & BigInt(4)    // 4n

BigNumber(-3).and(4).toString()    // '0'
```

BigNumber bitiwse operations need to match BigInt.

It's been a while since I looked at this but I remember working on it a bit and getting the results to match but I wasn't happy with the performance due to it using string operations and applying native bitwise ops one bit at a time. 

I currently have:

[bignumber.zip](https://github.com/MikeMcl/bignumber.js/files/9872762/bignumber.zip)

**Pull request closed without merging**
