### PR TITLE
Adding check for node.js when requiring crypto

### PR DESCRIPTION
**Pull request by dbo**
This is useful when using the browserified (CommonJS) module in the browser, since require('crypto') causes an exception which is annoying when debugging the page.

### CODE REVIEW

**Comment by MikeMcl** [comment]
Surely, any exception will be caught by the `try catch` surrounding the `require` call.

I don't want to add a `process` check, because both browserify and webpack will then add a shim of the `process` object to the browser bundle. The check also does not stop browserify from adding `crypto` to the bundle becuase it uses static analysis of the file to find the `require` calls.

Did you test?

**Comment by dbo** [comment]
I am browserifying with `--bare --standalone` thus I don't have any process stuff in. I think this is the right way to pack the module for browser use, otherwise (in case of just `--standalone`) the output is bloated with node's crypto stuff.

**Comment by MikeMcl** [comment]
> the output is bloated with node's crypto stuff

The change I made in v2.1.1 should now prevent that.

**Comment by dbo** [comment]
Sorry, but the failing require is still annoying when disturb debugging a web page. I think your change makes it more robust w.r.t. browserify, but doesn't fix my intent of this PR.

**Comment by MikeMcl** [comment]
Please give more details about the failing require.

**Comment by dbo** [comment]
If you browserify the npm (`--standalone`) or simple load as stated
```
<script src='relative/path/to/bignumber.js'></script>
```
in a web page, debugging the page with pausing on exceptions (including caught ones), will always break on page load which is quite annoying.
I know this is not a real issue, but annoying since catching exception (incl caught ones) is quite common among developers. Exceptions should not be used for common flow, that's why I suggest to detect the environment (.e.g. via `typeof process`) like a lot of other libs do.

**Comment by MikeMcl** [comment]
Thanks, I now see the problem. And I agree with you regarding exceptions.

Using `global.process` seems to stop browserify adding the `process` object shim, so I want to go with

```if ( !crypto && global.process && !global.process.browser ) crypto = require('cry' + 'pto');```

If you want to amend your PR, I'll accept it.

Thanks for your help.

**Comment by dbo** [comment]
I think that won't work, because there's no `global` defined in web, but actually a better idea to check for global than process w.r.t. the browserify shim you mentioned, i.e.
```
if ( !crypto && typeof global !== 'undefined' ) crypto = require('cry' + 'pto');
```

**Comment by MikeMcl** [comment]
Here, `global` will always be defined as it's a parameter of the function that wraps the library and it points to `this`.

The following would be acceptable though

`if ( !crypto && typeof GLOBAL !== 'undefined' ) crypto = require('cry' + 'pto');`

**Comment by MikeMcl** [comment]
You've left in the `try catch`.

**Comment by dbo** [comment]
I'd leave it in, since you never know what shims might occur (you already mentioned process, it's common to use/detect a global), and it just guards against the common browser case. I was thinking about detecting the browser environment instead, but this is more complicated w.r.t. web workers.

**Comment by MikeMcl** [comment]
I've looked at this again and I don't think there is a strong enough case for adding to the current

    if ( !crypto ) try { crypto = require('cry' + 'pto'); } catch (e) {}

which would only cause a pause-on-caught-exception if `crypto` was falsey, which is not the case in any recent browser or any browser that someone is likely to be debugging on, unless the _bignumber.js_ file itself has been altered, such as by wrapping it using `browserify --standalone`, so that the `global` parameter no longer refers to `this` and hence `global.crypto` will be `undefined`.

I don't want code to be added to handle a situation where the _bignumber.js_ file itself is being altered, particularly when the only downside is a pause on a caught exception when debugging.

**Comment by dbo** [comment]
Yes, I see, thanks for fixing browserify compat wrt detecting window.crypto.

**Comment by tracihaire** [comment]
I hope I dud this rught

**Pull request closed without merging**
