### PR TITLE
Feature: BigNumber.sum()

### LINKED ISSUE #187: Feature: BigNumber.sum()
PR submitted 😎 
Would love to see this in next release

#186

### PR DESCRIPTION
**Pull request by youfoundron**
Class method that returns a BigNumber sum of the passed arguments.

Closes #187

### CODE REVIEW

**Comment by rongierlach** [comment]
Adding tests / minified build shortly...

**Comment by rongierlach** [comment]
Alright, should be good to go 👍

**Comment by MikeMcl** [comment]
I will consider it, though it is going to be another month or so before I am able to look closely at this library again.

One issue is that I am committed to keeping this library compatible with JavaScript engines that only implement ECMAScript 3, so `reduce` and `const` would have to go.

**Comment by rongierlach** [comment]
Cool, I'll make those changes now.

**Comment by rongierlach** [comment]
@MikeMcl looks good to you?

**Comment by MikeMcl** [comment]
Sorry, but it's going to be a month before I can look at this properly and make a decision on it.

**Comment by MikeMcl** [comment]
I changed my mind on this. I think it's a worthwhile addition. Thanks.

**Pull request merged**
