### PR TITLE
Add missing 'new' to usage example

### PR DESCRIPTION
**Pull request by willnwhite**

### CODE REVIEW

**Comment by MikeMcl** [comment]
I think the omission of `new` was probably deliberate as it is optional if `BigNumber.set({ERRORS: false})`.

**Comment by willnwhite** [comment]
Okay. It was confusing to see the `constructor must be called with new` error and without new working in Usage. I've changed the PR to add the right information.

**Comment by MikeMcl** [comment]
I'd prefer just the commit which adds the 'new'.

**Comment by MikeMcl** [comment]
I've added the missing 'new'. Thanks for the report.

**Pull request closed without merging**
